### ISSUE TITLE
Endianness issues 

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/NetworkTablesDotNet#1]
For the robot code, we didn't have to do any byte swapping. However with network tables we are going to have to manually swap all the sent and received values. It works when running a C# server with a C# client, but a Python Server with a C# client, or a C# server with a Java client both fail because of endianness issues. It tries to send 0x0200 over the port, but over on the c# side we receive 0x0002 from this. Looking over at the C++ code, it looks like it is forcing BE, so we are going to have to as well. Looking around, it looks like there is no way to override streams, so I think we are going to have to make a custom BinaryReader and BinaryWriter to overload the write and read functions to always read and write big endian.

**Comment by jkoritzinsky** [comment]
Network byte order is big endian. We can use the HostToNetworkOrder methods on the IPAddress class to do most of the work.

**Comment by ThadHouse** [comment]
I don't think it was caused by endianess issues, but instead was caused by formatting issues. C++ used the raw streams and wrote a custom stream themselves on top of that, so I did that over here. That should work.

**Comment by ThadHouse** [comment]
Fixed in https://github.com/robotdotnet/NetworkTablesDotNet/commit/5d8ffc5e8d6be23c97c1243187c9b196f16af296
